CandleafShop/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    # path('discovery/<slug:category_slug>/', name='category'),
    path('products/<slug:detail_slug>/', views.detail, name='detail'),
    path('products/', views.discovery, name='discovery'),
    path('test/', views.test, name='test'),
]

users/urls.py
from django.urls import path
from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.registration, name='register'),
    path('profile/', views.profile, name='profile'),
]

products/models.py
from django.db import models
from django.urls import reverse


class Product(models.Model):

    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    description = models.CharField(max_length=500)
    quantity = models.IntegerField(default=20)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    image = models.ImageField(blank=True, upload_to='products/images')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    category = models.ForeignKey('Category', on_delete=models.PROTECT)

    objects = models.Manager()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-quantity']
        indexes = [
            models.Index(fields=['-quantity'])
        ]

    def get_absolute_url(self):
        return reverse('products:detail', kwargs={'detail_slug': self.slug})


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users/images', blank=True)

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Enter your password"}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your username"}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your First name"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "Enter your Last name"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': "Enter your email"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Create password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': "Repeat password"}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': True, 'class': 'read'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'readonly': True, 'class': 'read'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={
        'class': 'photo-change-button-input', 'value': 'Change photo', 'type': 'file', 'id': 'file-upload'
    }), required=False)

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'image')

products/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from .models import Product, Category


def index(request):
    products_data = Product.objects.all()
    context = {
        'mainpage_products': products_data[:8],
        'all_products': products_data,
        'popular_products': products_data[:4],
        'my_range': range(5),

    }
    return render(request, 'products/index.html', context=context)


def about(request):
    return render(request, 'products/about.html')


def detail(request, detail_slug):
    slug_detail = get_object_or_404(Product, slug=detail_slug)

    data = {
        'product': slug_detail,
    }
    return render(request, 'products/detail.html', context=data)


def discovery(request):
    products_data = Product.objects.all()
    context = {
        'all_products': products_data,
    }
    return render(request, 'products/discovery.html', context=context)


def sort_by_category(request, category_slug):
    category_info = get_object_or_404(Category, slug=category_slug)
    context = {
        'category': category_info,
    }
    return render(request, 'products/')


def test(request):
    return render(request, 'products/test.html')

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.contrib import auth

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('products:home'))

    else:
        form = UserLoginForm()

    context = {'form': form}
    return render(request, 'users/login.html', context=context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/register.html', context=context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, files=request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {'form': form}
    return render(request, 'users/profile.html', context=context)

products/templates/products/about.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/about.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="page-about-container">
    <div class="page-about">
        <p>
            Candleaf is an enchanting boutique nestled in a charming corner of the city, dedicated
            to the art and craft of candle making. As soon as you step into Candleaf, you're greeted
            by a warm, inviting atmosphere that immediately relaxes you. The walls are painted in soothing
            earth tones, and there's a gentle, subtle scent in the air – a blend of lavender, vanilla,
            and a hint of sandalwood.
        </p>

        <p>
            The shop features an extensive array of candles, each one handcrafted with meticulous care.
            The range includes everything from small, delicate tealights perfect for a cozy dinner table to large,
            statement pillar candles that can be the centerpiece of any room. The candles come in various shapes and
            sizes, and the variety of colors is a feast for the eyes - from deep, rich reds and blues to soft pastels
            and natural beeswax hues.
        </p>
        <p>
            One of the highlights of Candleaf is its selection of scented candles.
            These candles are made with natural essential oils and offer an array
            of fragrances, from the refreshing zest of citrus to the sweet allure
            of summer berries. Seasonal scents are also available, ensuring there's
            always something new to discover.
        </p>
        <p>
            In addition to candles, Candleaf also offers a range of candle-related accessories,
            such as elegant holders, snuffers, and wick trimmers, all designed to enhance your
            candle-burning experience.
        </p>
        <p>
            Candleaf isn't just a store; it's a haven for candle enthusiasts. The staff are knowledgeable and passionate
            about their craft. They offer workshops where customers can learn the art of candle making, from the basics
            of wax selection and scent blending to the skills needed to create beautifully layered candles.
        </p>
        <p>
            The shop also has a commitment to sustainability. They use eco-friendly materials and
            processes wherever possible, and many of their products are made from recycled or renewable resources.
        </p>
        <p>
            Candleaf is more than just a place to buy candles. It's an experience, a place where you can slow down,
            breathe in the tranquil atmosphere, and find the perfect candle to light up your life.
            Whether you're a candle aficionado or new to the world of candles, Candleaf welcomes you with open
            arms and a flickering flame.
        </p>
    </div>
</div>
{% endblock %}

products/templates/products/category.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/discovery.css' %}" rel="stylesheet" />
{% endblock %}


{% block body %}
<div class="discovery-products">
    <div class="products">
        {% for product in all_products %}
        {% include 'products/includes/product.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

products/templates/products/detail.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/detail.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="detail-container">
    <div class="detail-img">
        <img class="product-img" src="{{ product.image.url }}" alt="{{ product.name }}">
        <p>All hand-made with natural soy wax, Candleaf is <br>made for your pleasure moments.</p>
        <h1>🚚 FREE SHIPPING</h1>
    </div>
    <div class="detail-purchase">
        <h1>{{ product.name }} Candleaf&#174;</h1>
        <div class="purchase-container">
            <div class="price-quantity"></div>
            <div class="purchase-choices"></div>
        </div>
        <button class="add-to-cart">Add to cart</button>
        <div class="product-description">
            <p>{{ product.description}}</p>
        </div>
    </div>
</div>
{% endblock %}

products/templates/products/discovery.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/discovery.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div>Categories:</div>
<div class="discovery-products">
    <div class="products">
        {% for product in all_products %}
        {% include 'products/includes/product.html' %}
        {% endfor %}
    </div>
</div>
{% endblock %}

products/templates/products/includes/product.html
{% load static %}
<div class="product">
  <a href="{{ product.get_absolute_url }}"><div class="photo"><img src="{{ product.image.url }}" alt="{{ product.name }}"></div></a>
  <p class="name"><a class='a-name' href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
  <p class="price"><a class='a-price' href="{{ product.get_absolute_url }}">{{ product.price }}$</a></p>
</div>

products/templates/products/includes/stars.html
{% load static %}
{% for i in my_range %}
<img src="{% static 'products/images/star.png' %}">
{% endfor %}

products/templates/products/index.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'products/css/index.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="mainpage-image">
    <div class="mp-text">
        <h1>🌱</h1>
        <h1>The nature candle</h1>
        <h3>All handmade with natural soy wax, Candleaf is a companion for all your pleasure moments </h3>
        <button id="discoveryButton" data-static-url="{% url 'products:discovery' %}">Discovery our collection</button>
    </div>
</div>
<div class="products-text">
    <h1>Products</h1>
    <h3>Order it for you or for your beloved ones </h3>
</div>
<div class="prod-container">
    <div class="products">
        {% for product in mainpage_products %}
        {% include 'products/includes/product.html' %}
        {% endfor %}
    </div>
</div>
<div class="product-info">
    <div class="product-info-child">
        <div class="info-text">
            <h1>Clean and</h1>
            <h1>fragrant soy wax</h1>
            <p>Made for your home and for your wellness</p>
            <ul>
                <li><span>Eco-sustainable: </span>All recyclable materials, 0% CO2 emissions</li>
                <li><span>Hyphoallergenic: </span>100% natural, human friendly ingredients </li>
                <li><span>Handmade: </span>All candles are craftly made with love.</li>
                <li><span>Long burning: </span>No more waste. Created for last long.</li>
            </ul>
            <button id="aboutButton" data-static-url="{% url 'products:about' %}">Learn more</button>
        </div>
        <div class="info-image">
            <img  src="{% static 'products/images/info.png' %}">
        </div>
    </div>
</div>
<div class="testimonials">
    <h1>Testimonials</h1>
    <h3>Some quotes from our happy customers</h3>
    <div class="feedback-container">
        <div class="feedback">
            <img class="person" src="{% static 'products/images/luisa.png' %}">
            <div class="stars">
                {% include 'products/includes/stars.html' %}
            </div>
            <h1>“I love it! No more air</h1>
            <h2>fresheners”</h2>
            <h3>Luisa</h3>
        </div>
        <div class="feedback">
            <img class="person" src="{% static 'products/images/eduardo.png' %}">
            <div class="stars">
                {% include 'products/includes/stars.html' %}
            </div>
            <h1>“Raccomended for </h1>
            <h2>everyone”</h2>
            <h3>Edoardo</h3>
        </div>
        <div class="feedback">
            <img class="person" src="{% static 'products/images/mart.png' %}">
            <div class="stars">
                {% include 'products/includes/stars.html' %}
            </div>
            <h1>“Looks very natural, the</h1>
            <h2> smell is awesome”</h2>
            <h3>Mart</h3>
        </div>
    </div>
</div>

<div class="popular-product">
    <h1>Popular</h1>
    <h3>Our top selling product that you may like</h3>
    <div class="pop-product">
        {% for product in popular_products %}
        {% include 'products/includes/product.html' %}
        {% endfor %}
    </div>
</div>
<script src="{% static 'products/js/index.js' %}"></script>
{% endblock %}

products/templates/products/test.html
{% extends 'base.html'%}
{% load static %}

{% block body %}
<div id="div-id"></div>
<p>Хуй собачий добрій день</p>
<script src="{% static 'products/js/test.js' %}"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Candleaf</title>
    <link type="text/css" href="{% static 'products/css/style.css' %}" rel="stylesheet" />
    {% block css %} {% endblock %}
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css' />
</head>
<body>
<header>
        <nav class="navbar">
            <div class="container">
                <a href="{% url 'products:home' %}"><img src="{% static 'products/images/logo.png' %}" class="logo" alt="Candleaf" /></a>
                <div class="navbar-wrap">
                    <ul class="navbar-menu">
                        <li><a href="{% url 'products:discovery' %}">Discovery</a></li>
                        <li><a href="{% url 'products:about' %}">About us</a></li>
                        <li><a href="">Contact us</a></li>
                    </ul>
                </div>
                <div class="navbar-add">
                    <a href="{% url 'users:login' %}"><img src="{% static 'products/images/acc.png' %}" class="account" alt="account"></a>
                    <a href="#"><img src="{% static 'products/images/bask.png' %}" class="basket" alt="basket"></a>
                </div>
            </div>
        </nav>
</header>

{% block body %} {% endblock %}

<footer>
    <div class="footer-logo-container">
        <div class="footer-logo">
            <img src="{% static 'products/images/footer logo.png' %}" alt="Candleaf">
            <h3>Your natural candle made for<br /> your home and for your wellness.</h3>
        </div>
        <ul class="footer-ul">
            <li><span>Discovery</span></li>
            <li>New season</li>
            <li>Most searched</li>
            <li>Most selled</li>
        </ul>
        <ul class="footer-ul">
            <li><span>About</span></li>
            <li>Help</li>
            <li>Shipping</li>
            <li>Affiliate</li>
        </ul>
        <ul class="footer-ul">
            <li><span>Info</span></li>
            <li>Contact us</li>
            <li>Privacy Policies</li>
            <li>Terms & Conditions</li>
        </ul>
    </div>
</footer>

</body>
</html>

users/templates/users/login.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'users/css/login.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}

<div class="login-container">
    <form action="{% url 'users:login' %}" method="post" class="login-inputs-container">
        {% csrf_token %}
        <p class="container-title">Sign In</p>
        {{ form.username }}
        {{ form.password }}
        <div class="create-account">
            <button class="create-account-button">
                <a class="link" href="{% url 'users:register' %}">Create an Account</a>
            </button>
        </div>
        <div class="sign-in">
            <a class="link">
                <button class="sign-in-button" type="submit">Sign In</button>
            </a>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'users/css/profile.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="container">
    <form class="profile-container" action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="photo-container">
            <div class="photo">
                <img src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'users/images/user-avatar.png' %} {% endif %}" alt="">
            </div>
        </div>
        <label for="file-upload" class="photo-change-button">Change photo</label>
        {{ form.image }}
        <div class="profile-inputs-container">
            <label>First name:</label>
            {{ form.first_name }}
            <label>Last name:</label>
            {{ form.last_name }}
            <label>Email:</label>
            {{ form.email }}
            <label>Username:</label>
            {{ form.username }}
        </div>
        <button class="save-changes" type="submit">Save changes</button>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html'%}
{% load static %}

{% block css %}
<link type="text/css" href="{% static 'users/css/register.css' %}" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="register-container">
    <form action="{% url 'users:register' %}" method="post" class="register-inputs-container">
        {% csrf_token %}
        <p class="container-title">Create an Account</p>
        {{ form.username }}
        {{ form.first_name }}
        {{ form.last_name }}
        {{ form.email }}
        {{ form.password1 }}
        {{ form.password2 }}
        <div class="sign-in">
            <button class="sign-in-button" >
                <a class="link" href="{% url 'users:login' %}">Sign In</a>
            </button>
        </div>
        <div class="create-account">
            <button class="create-account-button" type="submit">Create an Account</button>
        </div>
    </form>
</div>
{% endblock %}